version: 2.1
orbs:
  node: circleci/node@5.1.0

executors:
  my-exe:
    docker:
      - image: cimg/node:19.8.0
        auth: 
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD

jobs:
  test:
    executor: my-exe
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: npm install
      - run:
          name: Rebuild
          command: npm rebuild
      - run: 
          name: Check Linting
          command: npm run lint
      - run: 
          name: Check Tests
          command:  npm run test
      - run:
          name: Upload App
          command: curl https://api.render.com/deploy/srv-chcj2dik728tp9ae2p50?key=9Wn84g85-G4

workflows:
    my-workflow:
      jobs:
        - test
